### ISSUE TITLE
noux 999.0.0 gives me an error message

### ISSUE THREAD

**Issue by AvangionQ** [Skrelpoid/SuperFastMode#36] opened 2019-06-01 17:09 UTC
noux 999.0.0 gives me an error message
says to go yell at the author to fix it
https://i.postimg.cc/hPNK1GvC/Slay-the-Spire-super-fast-mode-error.png

**Comment by Skrelpoid** [comment] 2019-06-01 18:36
I forgot to mark it as a prerelease, should be fixed, let me know if you still get the same message

**Comment by AvangionQ** [comment] 2019-06-02 16:49
Uh oh, same error message 😶

**Comment by Skrelpoid** [comment] 2019-06-02 18:32
Can you check if the issue is fixed now?

**Comment by AvangionQ** [comment] 2019-06-02 19:10
Working as intended ✅

**Closed** 2019-06-02 19:51 UTC
